{
 "title": "DNS Servers",
 "tags": [ "zabbix" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Hostname",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "General" },
     "group": { "filter": "Linux servers" },
     "host": { "filter": "DNS0 Server" },
     "item": { "filter": "Host name" },
     "mode": 2,
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "DNS Services",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Unbound" },
     "group": { "filter": "Linux servers" },
     "host": { "filter": "DNS0 Server" },
     "item": { "filter": "Unbound service" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Reboot Required",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "OS" },
     "functions": [
      {
       "def": {
        "category": "Aggregate",
        "defaultParams": [ "1m" ],
        "name": "average",
        "params": [
         { "name": "interval", "type": "string" }
        ]
       },
       "params": [ "1m" ],
       "text": "average(1m)"
      }
     ],
     "group": { "filter": "Linux servers" },
     "host": { "filter": "DNS0 Server" },
     "item": { "filter": "Reboot Required" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Multipathing Mapping",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "OS - Health" },
     "functions": [
      {
       "def": {
        "category": "Aggregate",
        "defaultParams": [ "1m" ],
        "name": "average",
        "params": [
         { "name": "interval", "type": "string" }
        ]
       },
       "params": [ "1m" ],
       "text": "average(1m)"
      }
     ],
     "group": { "filter": "Linux servers" },
     "host": { "filter": "DNS0 Server" },
     "item": { "filter": "Multipathing Device Mapping" },
     "mode": 2,
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "CPU Switches sps",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Performance" },
     "functions": [
      {
       "def": {
        "category": "Aggregate",
        "defaultParams": [ "1m" ],
        "name": "average",
        "params": [
         { "name": "interval", "type": "string" }
        ]
       },
       "params": [ "1m" ],
       "text": "average(1m)"
      }
     ],
     "group": { "filter": "Linux servers" },
     "host": { "filter": "DNS0 Server" },
     "item": { "filter": "Context switches per second" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Free Space on /",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 0 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "application": { "filter": "Filesystems" },
     "group": { "filter": "Linux servers" },
     "host": { "filter": "DNS0 Server" },
     "item": { "filter": "Free disk space on /" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Available memory",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 14, "y": 0 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Memory" },
     "group": { "filter": "Linux servers" },
     "host": { "filter": "DNS0 Server" },
     "item": { "filter": "Available memory" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Memory Temp",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 16, "y": 0 },
   "format": "celsius",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Power" },
     "functions": [
      {
       "def": {
        "category": "Aggregate",
        "defaultParams": [ "1m" ],
        "name": "average",
        "params": [
         { "name": "interval", "type": "string" }
        ]
       },
       "params": [ "1m" ],
       "text": "average(1m)"
      }
     ],
     "group": { "filter": "Linux servers" },
     "host": { "filter": "VirtualSRV Server" },
     "item": { "filter": "/.*-P1 Mem Zone/" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Memory Error",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Health" },
     "functions": [
      {
       "def": {
        "category": "Aggregate",
        "defaultParams": [ "1m" ],
        "name": "average",
        "params": [
         { "name": "interval", "type": "string" }
        ]
       },
       "params": [ "1m" ],
       "text": "average(1m)"
      }
     ],
     "group": { "filter": "Linux servers" },
     "host": { "filter": "VirtualSRV Server" },
     "item": { "filter": "Memory" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Process",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Processes" },
     "group": { "filter": "Linux servers" },
     "host": { "filter": "DNS0 Server" },
     "item": { "filter": "Number of processes" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Power Supply 1",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Power" },
     "functions": [
      {
       "def": {
        "category": "Aggregate",
        "defaultParams": [ "1m" ],
        "name": "average",
        "params": [
         { "name": "interval", "type": "string" }
        ]
       },
       "params": [ "1m" ],
       "text": "average(1m)"
      }
     ],
     "group": { "filter": "Linux servers" },
     "host": { "filter": "VirtualSRV Server" },
     "item": { "filter": "Power Supply 1" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Server UP Time",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 2 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "OS" },
     "group": { "filter": "Linux servers" },
     "host": { "filter": "DNS0 Server" },
     "item": { "filter": "System uptime" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "DNS Services UP Time",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 2 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Unbound" },
     "group": { "filter": "Linux servers" },
     "host": { "filter": "DNS0 Server" },
     "item": { "filter": "Unbound Uptime" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Dmesg Health",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 2 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "OS - Health" },
     "functions": [
      {
       "def": {
        "category": "Aggregate",
        "defaultParams": [ "1m" ],
        "name": "average",
        "params": [
         { "name": "interval", "type": "string" }
        ]
       },
       "params": [ "1m" ],
       "text": "average(1m)"
      }
     ],
     "group": { "filter": "Linux servers" },
     "host": { "filter": "DNS0 Server" },
     "item": { "filter": "Linux Kernel Dmesg Health" },
     "mode": 2,
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "CPU Switches sps",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 2 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Performance" },
     "functions": [
      {
       "def": {
        "category": "Aggregate",
        "defaultParams": [ "1m" ],
        "name": "average",
        "params": [
         { "name": "interval", "type": "string" }
        ]
       },
       "params": [ "1m" ],
       "text": "average(1m)"
      }
     ],
     "group": { "filter": "Linux servers" },
     "host": { "filter": "DNS0 Server" },
     "item": { "filter": "Interrupts per second" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Free Space on /boot",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 2 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "application": { "filter": "Filesystems" },
     "group": { "filter": "Linux servers" },
     "host": { "filter": "DNS0 Server" },
     "item": { "filter": "Free disk space on /boot" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Total memory",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 14, "y": 2 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Memory" },
     "group": { "filter": "Linux servers" },
     "host": { "filter": "DNS0 Server" },
     "item": { "filter": "Total memory" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "CPU Temp",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 16, "y": 2 },
   "format": "celsius",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Temp" },
     "functions": [
      {
       "def": {
        "category": "Aggregate",
        "defaultParams": [ "1m" ],
        "name": "average",
        "params": [
         { "name": "interval", "type": "string" }
        ]
       },
       "params": [ "1m" ],
       "text": "average(1m)"
      }
     ],
     "group": { "filter": "Linux servers" },
     "host": { "filter": "VirtualSRV Server" },
     "item": { "filter": "/.*-CPU*/" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Memory Temp",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 2 },
   "format": "celsius",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Power" },
     "functions": [
      {
       "def": {
        "category": "Aggregate",
        "defaultParams": [ "1m" ],
        "name": "average",
        "params": [
         { "name": "interval", "type": "string" }
        ]
       },
       "params": [ "1m" ],
       "text": "average(1m)"
      }
     ],
     "group": { "filter": "Linux servers" },
     "host": { "filter": "VirtualSRV Server" },
     "item": { "filter": "/.*-P1 Mem Zone/" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Running Process",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Processes" },
     "group": { "filter": "Linux servers" },
     "host": { "filter": "DNS0 Server" },
     "item": { "filter": "Number of running processes" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Power Supply 1",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Power" },
     "functions": [
      {
       "def": {
        "category": "Aggregate",
        "defaultParams": [ "1m" ],
        "name": "average",
        "params": [
         { "name": "interval", "type": "string" }
        ]
       },
       "params": [ "1m" ],
       "text": "average(1m)"
      }
     ],
     "group": { "filter": "Linux servers" },
     "host": { "filter": "VirtualSRV Server" },
     "item": { "filter": "Power Supply 2" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Space Availability",
   "type": "singlestat",
   "gridPos": { "h": 1, "w": 4, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Total Queries qbs",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Unbound" },
     "group": { "filter": "Linux servers" },
     "host": { "filter": "DNS0 Server" },
     "item": { "filter": "Unbound Total queries" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "System Load 5 minutes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Performance" },
     "group": { "filter": "Linux servers" },
     "host": { "filter": "DNS0 Server" },
     "item": {
      "filter": "Processor load (5 min average per core)"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Cache Performance",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "Unbound" },
     "group": { "filter": "Linux servers" },
     "host": { "filter": "DNS0 Server" },
     "item": { "filter": "Unbound Cache hits" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Unbound" },
     "group": { "filter": "Linux servers" },
     "host": { "filter": "DNS0 Server" },
     "item": { "filter": "Total Cachemiss" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Free space on /",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 5 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "application": { "filter": "Filesystems" },
     "group": { "filter": "Linux servers" },
     "host": { "filter": "DNS0 Server" },
     "item": {
      "filter": "Free disk space on / (percentage)"
     },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Free memory",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 5 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "application": { "filter": "Memory" },
     "group": { "filter": "Linux servers" },
     "host": { "filter": "DNS0 Server" },
     "item": { "filter": "Free Memory in %" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Cache hits qbs",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 7 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Unbound" },
     "group": { "filter": "Linux servers" },
     "host": { "filter": "DNS0 Server" },
     "item": { "filter": "Unbound Cache hits" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "MSG cache in memory",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 7 },
   "format": "decbits",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Unbound" },
     "group": { "filter": "Linux servers" },
     "host": { "filter": "DNS0 Server" },
     "item": { "filter": "Unbound Message cache memory" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Free Space on /boot",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 9 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "application": { "filter": "Filesystems" },
     "group": { "filter": "Linux servers" },
     "host": { "filter": "DNS0 Server" },
     "item": {
      "filter": "Free disk space on /boot (percentage)"
     },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Free Swap",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "application": { "filter": "Memory" },
     "group": { "filter": "Linux servers" },
     "host": { "filter": "DNS0 Server" },
     "item": { "filter": "Free swap space in %" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Cache Miss qbs",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 10 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Unbound" },
     "group": { "filter": "Linux servers" },
     "host": { "filter": "DNS0 Server" },
     "item": { "filter": "Total Cachemiss" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Interrupts per second",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 10 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "application": { "filter": "Performance" },
     "functions": [
      {
       "def": {
        "category": "Aggregate",
        "defaultParams": [ "1m" ],
        "name": "average",
        "params": [
         { "name": "interval", "type": "string" }
        ]
       },
       "params": [ "1m" ],
       "text": "average(1m)"
      }
     ],
     "group": { "filter": "Linux servers" },
     "host": { "filter": "DNS0 Server" },
     "item": { "filter": "Interrupts per second" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "application": { "filter": "CPU" },
     "group": { "filter": "Linux servers" },
     "host": { "filter": "DNS0 Server" },
     "item": { "filter": "/CPU (?!idle)/" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "DNS Memory Used",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 13 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "application": { "filter": "Unbound" },
     "group": { "filter": "Linux servers" },
     "host": { "filter": "DNS0 Server" },
     "item": { "filter": "Unbound Iterator module memory" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Unbound" },
     "group": { "filter": "Linux servers" },
     "host": { "filter": "DNS0 Server" },
     "item": { "filter": "Unbound Message cache memory" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Unbound" },
     "group": { "filter": "Linux servers" },
     "host": { "filter": "DNS0 Server" },
     "item": { "filter": "Unbound RRset cache memory" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Unbound" },
     "group": { "filter": "Linux servers" },
     "host": { "filter": "DNS0 Server" },
     "item": {
      "filter": "Unbound Validator module and key cache memory"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "DNS traffic and cache hits",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "Unbound" },
     "group": { "filter": "Linux servers" },
     "host": { "filter": "DNS0 Server" },
     "item": { "filter": "Unbound Cache hits" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Unbound" },
     "group": { "filter": "Linux servers" },
     "host": { "filter": "DNS0 Server" },
     "item": { "filter": "Unbound Total queries" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "Unbound" },
     "group": { "filter": "Linux servers" },
     "host": { "filter": "DNS0 Server" },
     "item": { "filter": "/(.*?ms)(?!.total)/" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "DNS queries by flags",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "Unbound" },
     "group": { "filter": "Linux servers" },
     "host": { "filter": "DNS0 Server" },
     "item": { "filter": "/.*flag/" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  }
 ]
}